# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2018-01-20 09:48
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField()),
                ('host', models.URLField()),
                ('path', models.CharField(max_length=200)),
                ('method', models.CharField(max_length=10)),
                ('status', models.PositiveSmallIntegerField(null=True)),
                ('user_agent', models.CharField(max_length=200)),
                ('query_params', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
                ('request_data', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
                ('response_data', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
                ('time_initialized', models.DateTimeField(auto_now_add=True)),
                ('time_finalized', models.DateTimeField(null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
