# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2018-01-23 10:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drflog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entry',
            options={'verbose_name_plural': 'Entries'},
        ),
        migrations.AlterField(
            model_name='entry',
            name='ip',
            field=models.GenericIPAddressField(db_index=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='method',
            field=models.CharField(db_index=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='entry',
            name='path',
            field=models.CharField(db_index=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='entry',
            name='status',
            field=models.PositiveSmallIntegerField(db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='user_agent',
            field=models.CharField(db_index=True, max_length=200),
        ),
    ]
